### PR TITLE
Csschanges

### PR DESCRIPTION
**Pull request by stavros-0**
#5

### CODE REVIEW

**Comment by stavros-0** [comment]
If the red navbar does not look good, I found that a grey color for the navbar would be a good option to consider. The logo is more readable with a grey color.

**Comment by miabonardi** [comment]
@stavros-0 the files are not attached

**Review by miabonardi — CHANGES_REQUESTED** [review]
Looks good so far. Just these two things I noticed should be changed to theme colors. 

Screen Shot 2023-10-10 at 8 23 24 AM

@nonprofittechy should review this also.

**Comment by miabonardi** [comment]
@stavros-0 Ask Michelle for the css of this interview interviews.gbls.org/run/sealing and incorporate it into this one, per Quinten

**Comment by miabonardi** [comment]
@stavros-0 this is looking better! Final change I think it to remove the logo and make the title like it is in the other interview and just have it say "Letter Suite" for now

**Review by miabonardi — APPROVED** [review]
Looks great!

**Pull request merged**
